### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by chiefcomm**
Added version key to be compliant with Home Assistant - addresses issue #56

### CODE REVIEW

**Comment by mk-maddin** [comment]
please implement as: ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'variable'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'variable'

**Comment by Mariusthvdb** [comment]
you should simply add that to your local manifest, as this Repo is no longer maintained, and the owner has long since got quiet.

**Comment by chiefcomm** [comment]
after persisting with this addon I've decided to switch to another https://github.com/snarky-snark/home-assistant-variables does everything and more - I suggest switching.

**Comment by Mariusthvdb** [comment]
just as a FYI, there is a current fork which is active and maintained: https://github.com/Wibias/hass-variables

and, the 2 are not identical, hass-variables allows for the history attributes, which [isn't supported](https://github.com/snarky-snark/home-assistant-variables/issues/53) on the snarky integration.

**Pull request closed without merging**
